[package]
name = "httplib"
version = "1.0.0"
edition = "2021"
authors = ["Slipum"]
description = "Lightweight HTTP server and router built in Rust"
license = "MIT"
repository = "https://github.com/Slipum/httplib"
readme = "README.md"
keywords = ["http", "server", "web", "framework", "router"]
categories = ["web-programming::http-server", "network-programming"]

[dependencies]
chrono = "0.4"